app:
  config:
    achizitiimd:
      cron: 0 0 10 * * *
      tenderListUrl: "https://achizitii.md/ru/public/tender/list?page="

spring:
  datasource:
    url: jdbc:postgresql://192.168.88.90:5432/data_miner
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase.enabled: true
  liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml