app:
  config:
    achizitiimd:
      cron: ${CRON_NEW}
      update: ${CRON_UPDATE}
      tenderListUrl: "https://achizitii.md/ru/public/tender/list?page=None"
      customerTenderList: "https://achizitii.md/ru/organization/idno/"

spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH}/data_miner
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase.enabled: true
  liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml
  codec:
    max-in-memory-size: 10MB